<?php

namespace App\Helpers\Appointment;

use Illuminate\Support\Facades\Storage;
use Illuminate\Http\Request;
use App\Helpers\GetIP;
use App\Models\Appointments\UserAppointments;
use App\Models\Appointments\PatientAppointmentsTemporary;
use Carbon\Carbon;

use Illuminate\Support\Str;
use Illuminate\Support\Facades\Hash;

use Illuminate\Support\Facades\Cache;

class RegistryHelper
{


    public function updateOrCreatePatientMaster($patientData, $patient_Id, $payload)
    {
        return
            [

                'patient_Id' => $patient_Id,
                'title_id' => $payload['title_id'] ?? null,
                'lastname' => $patientData['lastname'] ?? null,
                'firstname' => $patientData['firstname'] ?? null,
                'middlename' => $patientData['middlename'] ?? null,
                'suffix_id' => $patientData['suffix_id'] ?? null,
                'typeofbirth_id' => $payload['typeofbirth_id'] ?? null,
                'birthdate' => $patientData['birthdate'] ?? null,
                'birthtime' => $payload['birthtime'] ?? null,
                'birthplace' => $patientData['birthplace'] ?? null,
                'age' => $patientData['age'] ?? null,
                'sex_id' => $patientData['sex_Id'] ?? null,
                'nationality_id' => $patientData['nationality_Id'] ?? null,
                'citizenship_id' => $payload['citizenship_id'] ?? null,
                'complexion' => $payload['complexion'] ?? null,
                'haircolor' => $payload['haircolor'] ?? null,
                'eyecolor' => $payload['eyecolor'] ?? null,
                'height' => $payload['height'] ?? null,
                'weight' => $payload['weight'] ?? null,
                'religion_id' => $patientData['religion_Id'] ?? null,
                'civilstatus_id' => $patientData['civil_Status_Id'] ?? null,
                'bloodtype_id' => $payload['bloodtype_id'] ?? null,
                'dialect_spoken' => $payload['dialect_spoken'] ?? null,
                'bldgstreet' => $patientData['bldgstreet'] ?? null,
                'region_id' => $patientData['region_Id'] ?? null,
                'province_id' => $patientData['province_Id'] ?? null,
                'municipality_id' => $patientData['municipality_Id'] ?? null,
                'barangay_id' => $patientData['barangay_Id'] ?? null,
                'zipcode_id' => $patientData['zipcode_Id'] ?? null,
                'country_id' => $payload['country_id'] ?? null,
                'occupation' => $payload['occupation'] ?? null,
                'dependents' => $payload['dependents'] ?? null,
                'telephone_number' => $patientData['telephone_Number'] ?? null,
                'mobile_number' => $patientData['mobile_Number'] ?? null,
                'email_address' => $patientData['email_Address'] ?? null,
                'isSeniorCitizen' => $patientData['isSeniorCitizen'] ?? null,
                'SeniorCitizen_ID_Number' => $payload['SeniorCitizen_ID_Number'] ?? null,
                'isPWD' => $patientData['isPWD'] ?? null,
                'PWD_ID_Number' => $payload['PWD_ID_Number'] ?? null,
                'isPhilhealth_Member' => $payload['isPhilhealth_Member'] ?? null,
                'Philhealth_Number' => $payload['Philhealth_Number'] ?? null,
                'isEmployee' => $payload['isEmployee'] ?? null,
                'GSIS_Number' => $payload['GSIS_Number'] ?? null,
                'SSS_Number' => $payload['SSS_Number'] ?? null,
                'passport_number' => $payload['passport_number'] ?? null,
                'seaman_book_number' => $payload['seaman_book_number'] ?? null,
                'embarked_date' => $payload['embarked_date'] ?? null,
                'disembarked_date' => $payload['disembarked_date'] ?? null,
                'xray_number' => $payload['xray_number'] ?? null,
                'ultrasound_number' => $payload['ultrasound_number'] ?? null,
                'ct_number' => $payload['ct_number'] ?? null,
                'petct_number' => $payload['petct_number'] ?? null,
                'mri_number' => $payload['mri_number'] ?? null,
                'mammo_number' => $payload['mammo_number'] ?? null,
                'OB_number' => $payload['OB_number'] ?? null,
                'nuclearmed_number' => $payload['nuclearmed_number'] ?? null,
                'typeofdeath_id' => $payload['typeofdeath_id'] ?? null,
                'dateofdeath' => $payload['dateofdeath'] ?? null,
                'timeofdeath' => $payload['timeofdeath'] ?? null,
                'spDateMarried' => $payload['spDateMarried'] ?? null,
                'spLastname' => $payload['spLastname'] ?? null,
                'spFirstname' => $payload['spFirstname'] ?? null,
                'spMiddlename' => $payload['spMiddlename'] ?? null,
                'spSuffix_id' => $payload['spSuffix_id'] ?? null,
                'spAddress' => $payload['spAddress'] ?? null,
                'sptelephone_number' => $payload['sptelephone_number'] ?? null,
                'spmobile_number' => $payload['spmobile_number'] ?? null,
                'spOccupation' => $payload['spOccupation'] ?? null,
                'spBirthdate' => $payload['spBirthdate'] ?? null,
                'spAge' => $payload['spAge'] ?? null,
                'motherLastname' => $payload['motherLastname'] ?? null,
                'motherFirstname' => $payload['motherFirstname'] ?? null,
                'motherMiddlename' => $payload['motherMiddlename'] ?? null,
                'motherSuffix_id' => $payload['motherSuffix_id'] ?? null,
                'motherAddress' => $payload['motherAddress'] ?? null,
                'mothertelephone_number' => $payload['mothertelephone_number'] ?? null,
                'mothermobile_number' => $payload['mothermobile_number'] ?? null,
                'motherOccupation' => $payload['motherOccupation'] ?? null,
                'motherBirthdate' => $payload['motherBirthdate'] ?? null,
                'motherAge' => $payload['motherAge'] ?? null,
                'fatherLastname' => $payload['fatherLastname'] ?? null,
                'fatherFirstname' => $payload['fatherFirstname'] ?? null,
                'fatherMiddlename' => $payload['fatherMiddlename'] ?? null,
                'fatherSuffix_id' => $payload['fatherSuffix_id'] ?? null,
                'fatherAddress' => $payload['fatherAddress'] ?? null,
                'fathertelephone_number' => $payload['fathertelephone_number'] ?? null,
                'fathermobile_number' => $payload['fathermobile_number'] ?? null,
                'fatherOccupation' => $payload['fatherOccupation'] ?? null,
                'fatherBirthdate' => $payload['fatherBirthdate'] ?? null,
                'fatherAge' => $payload['fatherAge'] ?? null,
                'portal_access_uid' => $payload['portal_access_uid'] ?? null,
                'portal_access_pwd' => $payload['portal_access_pwd'] ?? null,
                'isBlacklisted' => $payload['isBlacklisted'] ?? null,
                'blacklist_reason' => $payload['blacklist_reason'] ?? null,
                'isAbscond' => $payload['isAbscond'] ?? null,
                'abscond_details' => $payload['abscond_details'] ?? null,
                'is_old_patient' => $payload['is_old_patient'] ?? null,
                'patient_picture' => $payload['patient_picture'] ?? null,
                'patient_picture_path' => $payload['patient_picture_path'] ?? null,
                'branch_id' => $payload['branch_id'] ?? null,
                'previous_patient_id' => $payload['previous_patient_id'] ?? null,
                'medsys_patient_id' => $payload['medsys_patient_id'] ?? null,
                'createdBy' => $payload['createdBy'] ?? null,
                'created_at' => $payload['created_at'] ?? null,
                'updatedBy' => $payload['updatedBy'] ?? null,
                'updated_at' => $payload['updated_at'] ?? null,
            ];
    }
    public function UpdateOrCreateCaseNo($payload, $patient_Id, $case_No)
    {
        return [

            'branch_Id' => $payload['branch_Id'] ?? 1,
            'patient_Id' => $patient_Id,
            'case_No' => $case_No,
            'er_Case_No' => $payload['er_Case_No'] ?? null,
            'register_Source' => $payload['register_Source'] ?? 6,
            'register_Casetype' => $payload['register_Casetype'] ?? 1,
            'register_Link_Case_No' => $payload['register_Link_Case_No'] ?? null,
            'register_Case_No_Consolidate' => $payload['register_Case_No_Consolidate'] ?? null,
            'patient_Age' => $payload['patient_Age'] ?? null,
            'er_Bedno' => $payload['er_Bedno'] ?? null,
            'room_Code' => $payload['room_Code'] ?? null,
            'room_Rate' => $payload['room_Rate'] ?? 0,
            'mscAccount_Type' => $payload['mscAccount_Type'] ?? 1,
            'mscAccount_Discount_Id' => $payload['mscAccount_Discount_Id'] ?? 0,
            'mscAccount_Trans_Types' => $payload['mscAccount_Trans_Types'] ?? 6,
            'mscAdmission_Type_Id' => $payload['mscAdmission_Type_Id'] ?? null,
            'mscPatient_Category' => $payload['mscPatient_Category'] ?? null,
            'mscPrice_Groups' => $payload['mscPrice_Groups'] ?? 1,
            'mscPrice_Schemes' => $payload['mscPrice_Schemes'] ?? 1,
            'mscService_Type' => $payload['mscService_Type'] ?? null,
            'mscService_Type2' => $payload['mscService_Type2'] ?? null,
            'mscDiet_Meal_Id' => $payload['mscDiet_Meal_Id'] ?? null,
            'mscDisposition_Id' => $payload['mscDisposition_Id'] ?? 0,
            'mscTriage_level_Id' => $payload['mscTriage_level_Id'] ?? 0,
            'mscCase_Result_Id' => $payload['mscCase_Result_Id'] ?? 0,
            'mscCase_Indicators_Id' => $payload['mscCase_Indicators_Id'] ?? 0,
            'mscPrivileged_Card_Id' => $payload['mscPrivileged_Card_Id'] ?? 0,
            'mscBroughtBy_Relationship_Id' => $payload['mscBroughtBy_Relationship_Id'] ?? 0,
            'queue_Number' => $payload['queue_Number'] ?? 0,
            'arrived_Date' => $payload['arrived_Date'] ?? Carbon::today(),
            'registry_Userid' => $payload['registry_Userid'] ?? 'outpatient',
            'registry_Date' => Carbon::today() ?? null,
            'registry_Status' => $payload['registry_Status'] ?? 1,
            'registry_Hostname' => $payload['registry_Hostname'] ?? null,
            'discharged_Userid' => $payload['discharged_Userid'] ?? null,
            'discharged_Date' => $payload['discharged_Date'] ?? null,
            'discharged_Hostname' => $payload['discharged_Hostname'] ?? null,
            'billed_Userid' => $payload['billed_Userid'] ?? null,
            'billed_Date' => $payload['billed_Date'] ?? null,
            'billed_Remarks' => $payload['billed_Remarks'] ?? null,
            'billed_Hostname' => $payload['billed_Hostname'] ?? null,
            'mgh_Userid' => $payload['mgh_Userid'] ?? null,
            'mgh_Datetime' => $payload['mgh_Datetime'] ?? null,
            'mgh_Hostname' => $payload['mgh_Hostname'] ?? null,
            'untag_Mgh_Userid' => $payload['untag_Mgh_Userid'] ?? null,
            'untag_Mgh_Datetime' => $payload['untag_Mgh_Datetime'] ?? null,
            'untag_Mgh_Hostname' => $payload['untag_Mgh_Hostname'] ?? null,
            'isHoldReg' => $payload['isHoldReg'] ?? null,
            'hold_Userid' => $payload['hold_Userid'] ?? null,
            'hold_No' => $payload['hold_No'] ?? null,
            'hold_Date' => $payload['hold_Date'] ?? null,
            'hold_Remarks' => $payload['hold_Remarks'] ?? null,
            'hold_Hostname' => $payload['hold_Hostname'] ?? null,
            'isRevoked' => $payload['isRevoked'] ?? null,
            'revokedBy' => $payload['revokedBy'] ?? null,
            'revoked_Date' => $payload['revoked_Date'] ?? null,
            'revoked_Remarks' => $payload['revoked_Remarks'] ?? null,
            'revoked_Hostname' => $payload['revoked_Hostname'] ?? null,
            'dischargeNotice_Userid' => $payload['dischargeNotice_Userid'] ?? null,
            'dischargeNotice_Date' => $payload['dischargeNotice_Date'] ?? null,
            'dischargeNotice_Hostname' => $payload['dischargeNotice_Hostname'] ?? null,
            'hbps_PrintedBy' => $payload['hbps_PrintedBy'] ?? null,
            'hbps_Date' => $payload['hbps_Date'] ?? null,
            'hbps_Hostname' => $payload['hbps_Hostname'] ?? null,
            'informant_Lastname' => $payload['informant_Lastname'] ?? null,
            'informant_Firstname' => $payload['informant_Firstname'] ?? null,
            'informant_Middlename' => $payload['informant_Middlename'] ?? null,
            'informant_Suffix' => $payload['informant_Suffix'] ?? null,
            'informant_Address' => $payload['informant_Address'] ?? null,
            'informant_Relation_id' => $payload['informant_Relation_id'] ?? null,
            'guarantor_Id' => $payload['guarantor_Id'] ?? null,
            'guarantor_Name' => $payload['guarantor_Name'] ?? null,
            'guarantor_Approval_code' => $payload['guarantor_Approval_code'] ?? null,
            'guarantor_Approval_no' => $payload['guarantor_Approval_no'] ?? null,
            'guarantor_Approval_date' => $payload['guarantor_Approval_date'] ?? null,
            'guarantor_Validity_date' => $payload['guarantor_Validity_date'] ?? null,
            'guarantor_Approval_remarks' => $payload['guarantor_Approval_remarks'] ?? null,
            'isWithCreditLimit' => $payload['isWithCreditLimit'] ?? null,
            'guarantor_Credit_Limit' => $payload['guarantor_Credit_Limit'] ?? null,
            'isWithMultiple_Gurantor' => $payload['isWithMultiple_Gurantor'] ?? null,
            'gurantor_Mutiple_TotalCreditLimit' => $payload['gurantor_Mutiple_TotalCreditLimit'] ?? null,
            'isWithPhilHealth' => $payload['isWithPhilHealth'] ?? null,
            'mscPHIC_Membership_Type_id' => $payload['mscPHIC_Membership_Type_id'] ?? null,
            'philhealth_Number' => $payload['philhealth_Number'] ?? null,
            'isWithMedicalPackage' => $payload['isWithMedicalPackage'] ?? null,
            'medical_Package_Id' => $payload['medical_Package_Id'] ?? null,
            'medical_Package_Name' => $payload['medical_Package_Name'] ?? null,
            'medical_Package_Amount' => $payload['medical_Package_Amount'] ?? null,
            'chief_Complaint_Description' => $payload['chief_Complaint_Description'] ?? null,
            'impression' => $payload['impression'] ?? null,
            'admitting_Diagnosis' => $payload['admitting_Diagnosis'] ?? null,
            'discharge_Diagnosis' => $payload['discharge_Diagnosis'] ?? null,
            'preOperative_Diagnosis' => $payload['preOperative_Diagnosis'] ?? null,
            'postOperative_Diagnosis' => $payload['postOperative_Diagnosis'] ?? null,
            'surgical_Procedure' => $payload['surgical_Procedure'] ?? null,
            'triageNotes' => $payload['triageNotes'] ?? null,
            'triageDate' => $payload['triageDate'] ?? null,
            'isCriticallyIll' => $payload['isCriticallyIll'] ?? null,
            'illness_Type' => $payload['illness_Type'] ?? null,
            'attending_Doctor' => $payload['attending_Doctor'] ?? null,
            'attending_Doctor_fullname' => $payload['attending_Doctor_fullname'] ?? null,
            'bmi' => $payload['bmi'] ?? null,
            'weight' => $payload['weight'] ?? null,
            'weightUnit' => $payload['weightUnit'] ?? null,
            'height' => $payload['height'] ?? null,
            'heightUnit' => $payload['heightUnit'] ?? null,
            'bloodPressureSystolic' => $payload['bloodPressureSystolic'] ?? null,
            'bloodPressureDiastolic' => $payload['bloodPressureDiastolic'] ?? null,
            'temperatute' => $payload['temperatute'] ?? null,
            'pulseRate' => $payload['pulseRate'] ?? null,
            'respiratoryRate' => $payload['respiratoryRate'] ?? null,
            'oxygenSaturation' => $payload['oxygenSaturation'] ?? null,
            'isHemodialysis' => $payload['isHemodialysis'] ?? null,
            'isPeritoneal' => $payload['isPeritoneal'] ?? null,
            'isLINAC' => $payload['isLINAC'] ?? null,
            'isCOBALT' => $payload['isCOBALT'] ?? null,
            'isBloodTrans' => $payload['isBloodTrans'] ?? null,
            'isChemotherapy' => $payload['isChemotherapy'] ?? null,
            'isBrachytherapy' => $payload['isBrachytherapy'] ?? null,
            'isDebridement' => $payload['isDebridement'] ?? null,
            'isTBDots' => $payload['isTBDots'] ?? null,
            'isPAD' => $payload['isPAD'] ?? null,
            'isRadioTherapy' => $payload['isRadioTherapy'] ?? null,
            'typeOfBirth_id' => $payload['typeOfBirth_id'] ?? null,
            'isWithBaby' => $payload['isWithBaby'] ?? null,
            'isRoomIn' => $payload['isRoomIn'] ?? null,
            'birthDate' => $payload['birthDate'] ?? null,
            'birthTime' => $payload['birthTime'] ?? null,
            'newborn_Status_Id' => $payload['newborn_Status_Id'] ?? null,
            'mother_Case_No' => $payload['mother_Case_No'] ?? null,
            'isDiedLess48Hours' => $payload['isDiedLess48Hours'] ?? null,
            'isDeadOnArrival' => $payload['isDeadOnArrival'] ?? null,
            'isAutopsy' => $payload['isAutopsy'] ?? null,
            'typeOfDeath_id' => $payload['typeOfDeath_id'] ?? null,
            'dateOfDeath' => $payload['dateOfDeath'] ?? null,
            'timeOfDeath' => $payload['timeOfDeath'] ?? null,
            'barcode_Image' => $payload['barcode_Image'] ?? null,
            'barcode_Code_Id' => $payload['barcode_Code_Id'] ?? null,
            'barcode_Code_String' => $payload['barcode_Code_String'] ?? null,
            'isreferredFrom' => $payload['isreferredFrom'] ?? null,
            'referred_From_HCI' => $payload['referred_From_HCI'] ?? null,
            'referred_From_HCI_address' => $payload['referred_From_HCI_address'] ?? null,
            'referred_From_HCI_code' => $payload['referred_From_HCI_code'] ?? null,
            'mscAccount_Type' => $payload['mscAccount_Type'] ?? 1,

        ];
    }

    public function UpdateOrCreateCheckIn($payload, $appointment)
    {

        return [
            'branch_id' => $appointment['branch_id'] ?? 1,
            'appointment_ReferenceNumber' => $appointment['appointment_ReferenceNumber'],
            'patient_Id'  => $appointment['patient_id'],
            'case_No' => $appointment['case_no'],
            'checkin_Time' => Carbon::today(),
            'checkinby' => $payload['id'] ?? null,
            'status_Id' => $payload['status_Id'] ?? 2,
            'createdby' => $payload['id'] ?? null,
            'created_at' => Carbon::today()

        ];
    }
}
